title: TrueNAS SCALE Helper docs
description: TrueNAS SCALE Helper script to help automating various tasks in TrueNAS SCALE
theme: just-the-docs

url: https://kage-chan.github.io/TNSH

nav_enabled: true
heading_anchors: true

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
