title: TNSH docs
description: TrueNAS SCALE Helper script to help automating various tasks in TrueNAS SCALE
theme: just-the-docs

url: https://kage-chan.github.io/TNSH

nav_enabled: true
heading_anchors: true

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: note
    color: blue
  highlight:
    title: highlight
    color: yellow

aux_links:
  TNSH on GitHub: https://github.com/kage-chan/TNSH